### ISSUE TITLE
大佬，这个主题我用一用哈

### ISSUE THREAD

**Issue by konglinlin** [fan-lv/Fan#1]
这是我博客的连接：https://konglinlin.github.io
再次谢大佬提供的主题

**Comment by RuntuS** [comment]
Process failed: layout/post.pug
请问下你在换主题的时候出现了这个问题了吗？

**Comment by konglinlin** [comment]
有点小问题，解决了(づ ●─● )づ，不过忘了是什么问题了，好像是缺了个配置。。。

**Comment by fan-lv** [comment]
已优化代码，更新下代码应该就 OK 了
