### ISSUE TITLE
资源消耗好大啊

### ISSUE THREAD

**Issue by Suny95** [fan-lv/Fan#10]
资源消耗好大啊, 我mac电脑打开博客放一会  风扇转速飙升```关了博客就好了

**Comment by fan-lv** [comment]
> 资源消耗好大啊, 我mac电脑打开博客放一会 风扇转速飙升```关了博客就好了

测试了一下，当前标签页不在活动状态时，资源占用正常
<img width="543" alt="非活动状态" src="https://user-images.githubusercontent.com/24888867/57268116-298cde00-70b5-11e9-935b-0abf29616fac.png">
当前标签页为活动状态时候，cpu 占用还是有点高的
<img width="540" alt="活动状态" src="https://user-images.githubusercontent.com/24888867/57268106-20037600-70b5-11e9-8345-97f57b5b0245.png">

**Comment by Suny95** [comment]
我把动画去掉了，就直接使用无动画的主题吧！问了前端的人说canvas就是耗性能

**Comment by fan-lv** [comment]
> 我把动画去掉了，就直接使用无动画的主题吧！问了前端的人说canvas就是耗性能

是的，想要酷炫的效果就得牺牲性能，鱼与熊掌不可兼得，看自己的取舍吧

**Comment by Suny95** [comment]
嗯，就这样搞吧
