### ISSUE TITLE
建议去掉鼠标滚轮的惯性滚动效果

### ISSUE THREAD

**Issue by AlynxZhou** [fan-lv/Fan#19]
电脑上在鼠标滚轮滚动时似乎模拟了触摸屏的惯性滚动效果，但是触屏惯性是系统层次实现的，想停在某一具体位置只需点击屏幕，而在滚轮滚动时使用惯性滚动很难控制滚动到某一细节位置。建议去掉这个效果。

**Comment by fan-lv** [comment]
emmmm，这个需要改动代码，滚动惯性写在scorll.js文件里了
