### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Block4283** [fan-lv/Fan#20]
安装并设置主题后，本地打不开为什么
并且访问博客后无法显示

**Comment by fan-lv** [comment]
控制台有报错吗，有的话把报错的信息截图发一下

**Comment by wy310181909** [comment]
extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug
请问这个是什么原因呀

**Comment by fan-lv** [comment]
@wy310181909 说明中的 hexo-renderer-jade 依赖没有正确安装

**Comment by fan-lv** [comment]
> 扩展include / layout.pug块内容包括include / recent-posts.pug包含include / pagination.pug请问
> 这个是什么原因呀

说明中的 hexo-renderer-jade 依赖没有正确安装

**Comment by fan-lv** [comment]
> extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug
> 请问这个是什么原因呀

说明中的 hexo-renderer-jade 依赖没有正确安装

**Comment by Block4283** [comment]
感谢一直发邮件回答我的问题，因为这段时间很忙暂时不会弄了，谢谢。

发送自 Windows 10 版邮件应用

发件人: LvFan
发送时间: 2020年5月16日 11:01
收件人: fan-lv/Fan
抄送: LUFEY; Author
主题: Re: [fan-lv/Fan] 问题 (#20)

Closed #20.
