### ISSUE TITLE
layout.pug文件报错

### ISSUE THREAD

**Issue by LeoLee0097** [fan-lv/Fan#22]
Unhandled rejection TypeError: F:\Blog\themes\Fan\layout\includes\layout.pug:11
9|
10| - var pageDescription = page.description || page.title || config.description || ''

11| - var pageKeywords = (config.keywords || []).join(',')
12| - if (page.tags && page.tags.data) pageKeywords = page.tags.data.map(function(tag) {return tag.name;}).join(',')
13| - var pageAuthor = config.author + ',' + config.email
14| - var pageCopyright = config.copyright || config.author

(config.keywords || []).join is not a function

第11行报错，说不是一个类

**Comment by fan-lv** [comment]
@LeoLee0097 在config文件中找到keywords，看一下是不是输入了什么文本，它需要数组类型
![image](https://user-images.githubusercontent.com/24888867/82108184-557a7f00-975f-11ea-8a85-51683d77ba0b.png)

**Comment by fan-lv** [comment]
感谢指出🙏，已修复bug
