### ISSUE TITLE
首页启动服务一段时间后刷新文章没有的问题

### ISSUE THREAD

**Issue by sy70927222** [fan-lv/Fan#30]
启动服务后打开-效果图
![image](https://user-images.githubusercontent.com/24430431/92676213-b30c8a00-f353-11ea-85c0-44ee621d1b57.png)

过段时间后刷新页面-效果图
![image](https://user-images.githubusercontent.com/24430431/92676198-aa1bb880-f353-11ea-9378-c27d3d886ca4.png)

**Comment by fan-lv** [comment]
`hexo -s` 启动本地服务有时候会出现页面异常，部署到服务器之后就没问题了。如果还出现此问题，打开浏览器控制台看一下有没有什么报错信息

**Comment by sy70927222** [comment]
那应该是我本地启动服务有关，浏览器控制台没报错!
