### ISSUE TITLE
hexo5.0.0+版本toc不会跳转

### ISSUE THREAD

**Issue by Devil-Z** [fan-lv/Fan#31]
5.0.0+版的hexo在toc生成时会对中文toc-link进行编码，但是文章本体的toc-link地址不会编码。导致scroll.js的监听事件读取到的toc-link地址不匹配，无法正确的激活sidebar的toc。
我fork以后在sidebar.js最后加了一个对toc的toc-link的href进行decode的过程，sidebar就可以正常跳转和激活了。

**Comment by fan-lv** [comment]
可以提交一个pull request，我合并下代码，谢谢
