### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by DevilLucker** [fan-lv/Fan#4]
#Update
How to use localsearch or algolia? Can show me your config algolia or localsearch!!

**Comment by DevilLucker** [comment]
can u help me with teamviewer?? :(

**Comment by DevilLucker** [comment]
![Untitled](https://user-images.githubusercontent.com/47933673/54659101-1e7cef00-4b03-11e9-968a-ee679e2d4a1d.png)

**Comment by fan-lv** [comment]
Please refer to the official website tutorial to configure Algolia, or refer to this article:[Hexo 配置 Aloglia](https://www.lvfan.xyz/2019/03/25/Hexo-%E9%85%8D%E7%BD%AE-Aloglia/), localSearch has not been implemented for this version.
