### ISSUE TITLE
请教下为啥我在本地显示不出来呢

### ISSUE THREAD

**Issue by 123wg** [fan-lv/Fan#6]
页面上显示这个，不知道为啥，其它有pug标签的主题都试了，都不行
`extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug`

**Comment by fan-lv** [comment]
还有其他的报错信息吗，方便的话把日志文件发一份我[邮箱](mailto:15757856604@163.com)

**Comment by fan-lv** [comment]
该问题是由于 pug 的依赖全局安装导致的
