### ISSUE TITLE
可以适配移动端嘛？

### ISSUE THREAD

**Issue by CrazyBunQnQ** [fan-lv/Fan#9]
您好，很喜欢您这个主题，很漂亮，也很喜欢深色主题。

但是在手机上打开您的博客主页仍然是以 PC 端的方式打开的， 体验不太好，后期会优化嘛？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by fan-lv** [comment]
现在已经对移动端做了一些简单的适配处理了，后续有时间会考虑完整的适配一遍
